/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#3f493f",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "outline": "#6f7a6e",
        "outline-variant": "#becabc",
        "surface-tint": "#006d30",
        "primary": "#00652c",
        "on-primary": "#ffffff",
        "primary-container": "#15803d",
        "on-primary-container": "#d3ffd5",
        "inverse-primary": "#79db8d",
        "secondary": "#9b4500",
        "on-secondary": "#ffffff",
        "secondary-container": "#fd8a42",
        "on-secondary-container": "#682c00",
        "tertiary": "#005c8e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2075ae",
        "on-tertiary-container": "#eef5ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#95f8a7",
        "primary-fixed-dim": "#79db8d",
        "on-primary-fixed": "#00210a",
        "on-primary-fixed-variant": "#005323",
        "secondary-fixed": "#ffdbca",
        "secondary-fixed-dim": "#ffb68e",
        "on-secondary-fixed": "#331200",
        "on-secondary-fixed-variant": "#763300",
        "tertiary-fixed": "#cde5ff",
        "tertiary-fixed-dim": "#94ccff",
        "on-tertiary-fixed": "#001d32",
        "on-tertiary-fixed-variant": "#004b74",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "margin": "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-sm": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "body-sm": ["Be Vietnam Pro", "sans-serif"],
        "label-numeric": ["Space Grotesk", "sans-serif"],
        "label-badge": ["Space Grotesk", "sans-serif"],
        "caption": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-numeric": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "label-badge": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "caption": ["11px", { lineHeight: "14px", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
